services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-postgres-16
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ecommerce-postgres-data:/var/lib/postgresql/data

volumes:
  ecommerce-postgres-data:
    external: true
